{% set name = "airfly" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/airfly-{{ version }}.tar.gz
  sha256: b77f83a268aede1be099d59160b86433a40c5e8004af59008cd6c66e5a4501f7

build:
  entry_points:
    - airfly = airfly.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7,<4.0
    - asttrs >=0.7.0,<0.8.0
    - attrs
    - black
    - click
    - isort
    - networkx
    - regex

test:
  imports:
    - airfly
  commands:
    - pip check
    - airfly --help
  requires:
    - pip

about:
  home: https://github.com/ryanchao2012/airfly
  summary: Auto generate Airflow's dag.py on the fly
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
